FIX: pp: properly handle None returned in error path
pp returns None instead of data results in error path.
Unfortunately this fix seems to uncover a bug in pp.

Alas, it still seems to be an improvement.

>>> import mdp.parallel as parallel
>>> scheduler = parallel.pp_support.LocalPPScheduler(ncpus=2, max_queue_length=0, verbose=True)
>>> for i in range(50): scheduler.add_task(i, parallel.SqrTestCallable())
...
A fatal error has occured during the function execution
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/ppworker.py", line 93, in run
    __args = pickle.loads(__sargs)
  File "/home/zbyszek/mdp/mdp-toolkit/mdp/__init__.py", line 118, in <module>
    numx_rand, numx_version) = configuration.get_numx()
  File "/home/zbyszek/mdp/mdp-toolkit/mdp/configuration.py", line 169, in get_numx
    raise ImportError('\n'.join(msg))
ImportError: Could not import any of the numeric backends.
Import errors:
scipy: No module named multiarray
numpy: No module named multiarray
sys.path: ['/usr/share/pyshared', '/home/zbyszek/mdp/mdp-toolkit', '/usr/local/lib/python2.6/dist-packages/Trac-0.12-py2.6.egg', '/usr/local/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode', '/usr/local/lib/python2.6/dist-packages/pytools-10-py2.6.egg', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/lib-old', '/usr/local/lib/python2.6/dist-packages/pyopencl-0.92-py2.6-linux-x86_64.egg', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/python2.6/lib-tk', '/usr/local/lib/python2.6/dist-packages/TracAccountManager-0.2.1dev_r4679-py2.6.egg', '/usr/lib/python2.6', '/usr/local/lib/python2.6/dist-packages/TracGit-0.12.0.2dev_r7757-py2.6.egg', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-old']
    task failed
A fatal error has occured during the function execution
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/ppworker.py", line 93, in run
    __args = pickle.loads(__sargs)
  File "/home/zbyszek/mdp/mdp-toolkit/mdp/__init__.py", line 118, in <module>
    numx_rand, numx_version) = configuration.get_numx()
  File "/home/zbyszek/mdp/mdp-toolkit/mdp/configuration.py", line 169, in get_numx
    raise ImportError('\n'.join(msg))
ImportError: Could not import any of the numeric backends.
Import errors:
scipy: No module named multiarray
numpy: No module named multiarray
sys.path: ['/usr/share/pyshared', '/home/zbyszek/mdp/mdp-toolkit', '/usr/local/lib/python2.6/dist-packages/Trac-0.12-py2.6.egg', '/usr/local/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/wx-2.8-gtk2-unicode', '/usr/local/lib/python2.6/dist-packages/pytools-10-py2.6.egg', '/usr/lib/pymodules/python2.6/gtk-2.0', '/usr/lib/pymodules/python2.6', '/usr/lib/python2.6/lib-old', '/usr/local/lib/python2.6/dist-packages/pyopencl-0.92-py2.6-linux-x86_64.egg', '/usr/lib/python2.6/dist-packages', '/usr/lib/python2.6/dist-packages/gst-0.10', '/usr/lib/python2.6/lib-tk', '/usr/local/lib/python2.6/dist-packages/TracAccountManager-0.2.1dev_r4679-py2.6.egg', '/usr/lib/python2.6', '/usr/local/lib/python2.6/dist-packages/TracGit-0.12.0.2dev_r7757-py2.6.egg', '/usr/lib/python2.6/lib-dynload', '/usr/lib/python2.6/dist-packages/PIL', '/usr/lib/python2.6/plat-linux2', '/usr/lib/python2.6/lib-old']
    task failed
Exception in thread run_local:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pymodules/python2.6/pp.py", line 721, in _run_local
    job.finalize(sresult)
UnboundLocalError: local variable 'sresult' referenced before assignment