OTH: added failing test for no eigenvalues left problem.
When PCANode is set to use SVD and automatic dimensionality reduction
it may happen that after removing directions corresponding to
eigenvalues smaller than var_abs (1e-12 default), nothing is left.
This happens for example if the data is a matrix of (almost) zeros.
The error looks like this:
Traceback (most recent call last):
[...]
File ".../mdp/nodes/pca_nodes.py", line 220, in _stop_training
    d = d[ d / d.max() > self.var_rel ]
ValueError: zero-size array to ufunc.reduce without identity