FIX: fix sklearn wrappers for version 0.10
New sklearn version introduces classifiers and predictors
mixin classes that do not have a 'fit' method. Typical error:

AttributeError: type object 'OutlierDetectionMixin' has no attribute 'fit'

Just added a check that the method is really present before wrapping.