FIX: old joblib breaks imports from sklearn.decomposition
>>> import sklearn.decomposition
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/pymodules/python2.6/sklearn/decomposition/__init__.py", line 8, in <module>
    from .sparse_pca import SparsePCA, MiniBatchSparsePCA
  File "/usr/lib/pymodules/python2.6/sklearn/decomposition/sparse_pca.py", line 10, in <module>
    from .dict_learning import dict_learning, dict_learning_online
  File "/usr/lib/pymodules/python2.6/sklearn/decomposition/dict_learning.py", line 17, in <module>
    from ..externals.joblib import Parallel, delayed, cpu_count
ImportError: cannot import name cpu_count
>>> joblib.__version__
'0.4.3'